HomeWork 2
ZalyalovIldar/Lesson2- pull request #6
Opened 2019-10-01 15:11 UTC by romashonly

Шуркин Роман 11-801

2019-10-01 16:10 UTC, ZalyalovIldar requested changes
В целом норм, но помимо комментов еще подправь скролл для SE, чет там по горизонтали скроллить можно

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/EditStatusViewController.swift
> +        // Do any additional setup after loading the view.
удалить коммент

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ViewController.swift
> +    @IBOutlet weak var giftThirdImage: UIImageView?
почему опциональные? Аутлеты должны быть с форсом ж

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ViewController.swift
> +        super.viewWillAppear(true)
не тру передавать, а animated параметр)

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ViewController.swift
> +    var modelController: ModelController! = ModelController()
если тут же инитишь, форсить не нужно)

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ViewController.swift
> +        if modelController.textOfStatus == "Измените статус" {
текст в константы

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ViewController.swift
> +            statusLabel?.textColor = UIColor(red: 0, green: 0, blue: 0, alpha: 1)
можно задать просто цвет, через UIColor.white/UIColor.black и т.д.

2019-10-01 16:10 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ModelController.swift
> +class ModelController {
это модель же, используй struct, и обзови понятнее)

2019-10-01 16:47 UTC, ZalyalovIldar commented
еще аватар обрезается, тоже посмотри на разных факторах

2019-10-01 17:32 UTC, romashonly commented on Homework/VkProfile/VkProfile/Controllers/ModelController.swift
> +class ModelController {
Если будет struct, то при передачи между контроллерами он же будет копироваться, а не ссылаться, и измененный статус(текст) не будет передаваться, разве нет?

2019-10-02 12:00 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ModelController.swift
> +class ModelController {
верно, но стоит придерживать концепции не мьютабельности при работе с данными, и изменения возвращать другими способами

2019-10-02 12:01 UTC, ZalyalovIldar commented on Homework/VkProfile/VkProfile/Controllers/ModelController.swift
> +class ModelController {
верно, но стоит придерживать концепции не мьютабельности при работе с данными, и изменения возвращать другими способами

2019-10-04 14:38 UTC, closed without merging