homework 2
ZalyalovIldar/Lesson2- pull request #9
Opened 2019-10-01 18:54 UTC by underqcool

Мялицин Максим

2019-10-01 19:00 UTC, underqcool commented
кнопка изменения статуса пока нерабочая и приводит к крашу, ищу решение

2019-10-12 15:35 UTC, ZalyalovIldar requested changes
Кроме комментов: 
1) Едет верстка на SE 🐛 
2) Лишняя высота скролла 🐞  
3) При нажатии на статус падает 🐛

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/EditStatusViewController.swift
> +        configure(with: user)
вот из-за этого падает)

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/EditStatusViewController.swift
> +       var user: User!
у кого то из них не верная табуляция

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/EditStatusViewController.swift
> +       var user: User!
+ отступ между аутлетом и переменной

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/ViewController.swift
> +    @IBOutlet weak var ContactsLabel: UILabel!
все переменные с маленькой буквы

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/ViewController.swift
> +        onllineLabel.text = user.isOnline ? "online" : "offline"
в константы текст

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/ViewController.swift
> +        if segue.identifier == "editStatusSegue" {
в константы

2019-10-12 15:35 UTC, ZalyalovIldar commented on Lesson2/ViewControllers/ViewController.swift
> +        scrollView.contentSize.height = scrollView.getHeight() + 150
кажется 150 лишняя, т.к. у скролла есть лишняя высота

2019-10-29 12:41 UTC, closed without merging